### ISSUE TITLE
logins failed , if the user password contains any letter

### ISSUE THREAD

**Issue by bhzhu203** [ufukty/ovpn-auth#3] opened 2024-05-07 09:11 UTC
I have tested that If the user password contains any letter , logins will be failed .

Like this:

zhenyi2   7758258+totp  success
zhenyi3   7758a+totp    failed 

```
2024-05-07 17:02:43 10.10.10.139:44290 TLS Auth Error: Auth Username/Password verification failed for peer
2024-05-07 17:02:43 10.10.10.139:44290 [5af3e3483f892a016098f0fd] Peer Connection Initiated with [AF_INET6]::ffff:10.10.10.139:44290
2024-05-07 17:02:44 10.10.10.139:44290 Connection reset, restarting [0]
2024-05-07 17:03:06 TCP connection established with [AF_INET6]::ffff:10.10.10.139:35912
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_VER=2.4.6
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_PLAT=linux
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_PROTO=2
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_NCP=2
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_LZ4=1
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_LZ4v2=1
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_LZO=1
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_COMP_STUB=1
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_COMP_STUBv2=1
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_TCPNL=1
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_HWADDR=00:e0:70:d7:7c:ed
2024-05-07 17:03:07 10.10.10.139:35912 peer info: IV_SSL=OpenSSL_1.0.2j__26_Sep_2016
2024-05-07 17:03:07 10.10.10.139:35912 peer info: UV_ID=f8c382c7c2354c8a9a71266e9ae62b08
2024-05-07 17:03:07 10.10.10.139:35912 peer info: UV_NAME=lively-meadow-2754
checking login: password mismatch
2024-05-07 17:03:07 10.10.10.139:35912 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 1
```

```
cat ovpn_auth_database.yml
- username: zhenyi
  hash: $argon2id$v=19$m=65536,t=2,p=1$luXe042DwRxBvTQSBWy4jce7IzSxPEfEbZZlNUzR3I0$2A9ImneJVC5CBtpvsMhiMbvxcYTPTTyKB5zLH6q87RZKDYmCGpYII6shKPoD/wh53+F5XcgF/7mKvGFclnWrmo9SwJq9rZYUlcrK/OC7anHCZtFjtlZ3PngUf/HnVyHFXMmUB3VWwYuiYUj1yoz9NqsJ5JKLgK1AQ4zAiaJU5Os
  totp-secret: DUGERAEY37VCSLKTJ7LENNNXUEK6NL5H
- username: dhb
  hash: $argon2id$v=19$m=65536,t=2,p=1$YfWvM670zlZ6tNe2Vv+4eY2u8Rp+9nafDZgwiS+b1OY$25d37H7YvDXytRiwzB+4vZRN9Uk/38LSsypLE+yING2jE4fBT/BBWjBWCiPwFuSh6zoYcOCUuhYA578k5W1m0wuRSYFEdcG3bCpN0eVLTilgUh+2WIBNDzy3iaSiSrN89/VjyYw2Zg+nV6K9iIIEDdOr1zWgs+uSz9dZDIlNkSo
  totp-secret: 47MAAS2RNMPZWG3EIJXROOHTOCXDWZI7
- username: zhenyi1
  hash: $argon2id$v=19$m=65536,t=2,p=1$b/eipPqXhsc2wtDg0B9CpDqY017W6QySLGsNLs8rdG4$1dYcBV2i7ujSMR9HxNM5mM8L8jDAqsH7/PqzxChTtRa7as21FcqvTX7gJ2cFgcM4LzOKLp2yRT8wDOgkrUxxmFRH7Q3YLF6cxniqTOTTuSYQZc6NhtWOIw7FwamlrYQtUKGy/mrta4z+BFlJCqorftxwv3Bw3cv8aR4WudbfvnI
  totp-secret: QW2EHNUBWZN5S3ARFPN55HE6HP25VCI7
- username: zhenyi2
  hash: $argon2id$v=19$m=65536,t=2,p=1$RoC5AJXmQ7L1QEgqmC4b0SuaSphN1Nw4Nsc7qT6mjyg$R4pU0w8YtK7aT4lsHTP/bxdLzFuIXFlFu24DlBGFnM6ulqR4Ur+rzZaCVjI7ibEZhsfEdl/JhYohamsbAL0sFcs2Z99OcOLBYyqvsrqq5b9QAQz2jWxeQXoTvYU52PbeFn1xVqjK8XBu0ho5VbQoQXJxqOujXFQ4f6qVWy0oI48
  totp-secret: BGECEQRWO5LBH56IIQASBSZFHDTSXE7A
- username: zhenyi3
  hash: $argon2id$v=19$m=65536,t=2,p=1$l/sL8xe3IbyeoVHZBpEH7fO2gCOEWl+qE688i4lia4Q$Pg1XWEvE2qO+NKRVOmtz6r1XgDTdu70gJBhmKpvGdjbBd3Ed3QnmjWZC3iJJuwnISW07K484pQWPiummguyFpjX7GZFcLzfVqQ9cpLLti1EjpjTViZ2OGRdQELfftKNddkEZ/IlHb8d9uFjtEXjbYOaZbVOvsRPStVQ263ZnDo4
  totp-secret: FLUOBRVC2HK73TUGHUCD4N63WNBDV5QO
```

Sencond ,

Server showing some errors when input wrong password and username

```
2024-05-07 16:46:41 10.10.10.139:44008 peer info: UV_NAME=lively-meadow-2754
panic: runtime error: slice bounds out of range [:-5]

goroutine 1 [running]:
github.com/ufukty/ovpn-auth/internal/files.ParseLoginRequest({0x7ffc668e99e4?, 0x41a716?})
	/root/ovpn-auth/internal/files/request.go:30 +0x332
github.com/ufukty/ovpn-auth/internal/login.WithFile({0x7ffc668e99e4?, 0x7f268789ee08?})
	/root/ovpn-auth/internal/login/login.go:64 +0x1c
main.dispatch()
	/root/ovpn-auth/cmd/ovpn-auth/main.go:39 +0x112
main.main()
	/root/ovpn-auth/cmd/ovpn-auth/main.go:48 +0x13
2024-05-07 16:46:41 10.10.10.139:44008 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 2
2024-05-07 16:46:41 10.10.10.139:44008 TLS Auth Error: Auth Username/Password verification failed for peer
2024-05-07 16:46:41 10.10.10.139:44008 [5af3e3483f892a016098f0fd] Peer Connection Initiated with [AF_INET6]::ffff:10.10.10.139:44008
2024-05-07 16:46:42 10.10.10.139:44008 Connection reset, restarting [0]
2024-05-07 16:46:59 TCP connection established with [AF_INET6]::ffff:10.10.10.139:51196
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_VER=2.4.6
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_PLAT=linux
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_PROTO=2
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_NCP=2
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_LZ4=1
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_LZ4v2=1
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_LZO=1
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_COMP_STUB=1
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_COMP_STUBv2=1
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_TCPNL=1
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_HWADDR=00:e0:70:d7:7c:ed
2024-05-07 16:47:00 10.10.10.139:51196 peer info: IV_SSL=OpenSSL_1.0.2j__26_Sep_2016
2024-05-07 16:47:00 10.10.10.139:51196 peer info: UV_ID=f8c382c7c2354c8a9a71266e9ae62b08
2024-05-07 16:47:00 10.10.10.139:51196 peer info: UV_NAME=lively-meadow-2754
panic: runtime error: slice bounds out of range [:-5]

goroutine 1 [running]:
github.com/ufukty/ovpn-auth/internal/files.ParseLoginRequest({0x7ffc488839e4?, 0x41a716?})
	/root/ovpn-auth/internal/files/request.go:30 +0x332
github.com/ufukty/ovpn-auth/internal/login.WithFile({0x7ffc488839e4?, 0x7f1a00f56e08?})
	/root/ovpn-auth/internal/login/login.go:64 +0x1c
main.dispatch()
	/root/ovpn-auth/cmd/ovpn-auth/main.go:39 +0x112
main.main()
	/root/ovpn-auth/cmd/ovpn-auth/main.go:48 +0x13
2024-05-07 16:47:00 10.10.10.139:51196 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 2
2024-05-07 16:47:00 10.10.10.139:51196 TLS Auth Error: Auth Username/Password verification failed for peer
2024-05-07 16:47:00 10.10.10.139:51196 [5af3e3483f892a016098f0fd] Peer Connection Initiated with [AF_INET6]::ffff:10.10.10.139:51196
2024-05-07 16:47:01 10.10.10.139:51196 Connection reset, restarting [0]
2024-05-07 16:47:14 TCP connection established with [AF_INET6]::ffff:10.10.10.139:46666
```

```
cat ovpn_auth_database.yml
- username: zhenyi
  hash: $argon2id$v=19$m=65536,t=2,p=1$luXe042DwRxBvTQSBWy4jce7IzSxPEfEbZZlNUzR3I0$2A9ImneJVC5CBtpvsMhiMbvxcYTPTTyKB5zLH6q87RZKDYmCGpYII6shKPoD/wh53+F5XcgF/7mKvGFclnWrmo9SwJq9rZYUlcrK/OC7anHCZtFjtlZ3PngUf/HnVyHFXMmUB3VWwYuiYUj1yoz9NqsJ5JKLgK1AQ4zAiaJU5Os
  totp-secret: DUGERAEY37VCSLKTJ7LENNNXUEK6NL5H
- username: dhb
  hash: $argon2id$v=19$m=65536,t=2,p=1$YfWvM670zlZ6tNe2Vv+4eY2u8Rp+9nafDZgwiS+b1OY$25d37H7YvDXytRiwzB+4vZRN9Uk/38LSsypLE+yING2jE4fBT/BBWjBWCiPwFuSh6zoYcOCUuhYA578k5W1m0wuRSYFEdcG3bCpN0eVLTilgUh+2WIBNDzy3iaSiSrN89/VjyYw2Zg+nV6K9iIIEDdOr1zWgs+uSz9dZDIlNkSo
  totp-secret: 47MAAS2RNMPZWG3EIJXROOHTOCXDWZI7
```

**Comment by ufukty** [comment] 2024-05-07 10:40
Can you confirm you wait the second prompt to enter password and TOTP nonce like

```
Enter Auth Username:zhenyi2
Enter Auth Password:7758aTOTP
```

If so, I will check [the code](https://github.com/ufukty/ovpn-auth/blob/b2f97194cd8a3b787f1a9d7be9a6e25330f67d63/internal/files/request.go#L30) in question later. 

Thanks for logs.

**Comment by bhzhu203** [comment] 2024-05-08 01:51
> Can you confirm you wait the second prompt to enter password and TOTP nonce like
> 
> ```
> Enter Auth Username:zhenyi2
> Enter Auth Password:7758aTOTP
> ```
> 
> If so, I will check [the code](https://github.com/ufukty/ovpn-auth/blob/b2f97194cd8a3b787f1a9d7be9a6e25330f67d63/internal/files/request.go#L30) in question later.
> 
> Thanks for logs.

Like these TOTP   473654  039177  293494

```
2024-05-08 09:48:56 10.10.10.139:55504 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 2
2024-05-08 09:48:56 10.10.10.139:55504 TLS Auth Error: Auth Username/Password verification failed for peer
2024-05-08 09:48:56 10.10.10.139:55504 [5af3e3483f892a016098f0fd] Peer Connection Initiated with [AF_INET6]::ffff:10.10.10.139:55504
2024-05-08 09:48:57 10.10.10.139:55504 Connection reset, restarting [0]
2024-05-08 09:49:37 TCP connection established with [AF_INET6]::ffff:10.10.10.139:59254
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_VER=2.4.6
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_PLAT=linux
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_PROTO=2
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_NCP=2
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_LZ4=1
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_LZ4v2=1
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_LZO=1
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_COMP_STUB=1
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_COMP_STUBv2=1
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_TCPNL=1
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_HWADDR=00:e0:70:d7:7c:ed
2024-05-08 09:49:38 10.10.10.139:59254 peer info: IV_SSL=OpenSSL_1.0.2j__26_Sep_2016
2024-05-08 09:49:38 10.10.10.139:59254 peer info: UV_ID=f8c382c7c2354c8a9a71266e9ae62b08
2024-05-08 09:49:38 10.10.10.139:59254 peer info: UV_NAME=lively-meadow-2754
checking login: password mismatch
2024-05-08 09:49:38 10.10.10.139:59254 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 1
2024-05-08 09:49:38 10.10.10.139:59254 TLS Auth Error: Auth Username/Password verification failed for peer
2024-05-08 09:49:38 10.10.10.139:59254 [5af3e3483f892a016098f0fd] Peer Connection Initiated with [AF_INET6]::ffff:10.10.10.139:59254
2024-05-08 09:49:39 10.10.10.139:59254 Connection reset, restarting [0]
```

**Comment by ufukty** [comment] 2024-05-10 15:02
I've just tried logging in to a OpenVPN server using ovpn-auth and a password that contains letters, digits and symbols. Since it worked as before, I can say I could not reproduce your issue. 

I suggest you to: 

* Check your inputs. Users are not supposed to enter their passwords until OpenVPN client explicitly prompts as `Enter Auth Password:`. If you enter your password by appending to your username that might be the problem.
* Check your server and client configuration files. Server needs to have this line: 
    ```
    auth-user-pass-verify /etc/openvpn/ovpn-auth via-file
    ```
    and the client config .ovpn file should have this line:
    ```
    auth-user-pass
    ```
* Replace the ovpn-auth binary with a script that will print out (`cat $1`) the content of file which its path passed by OpenVPN. So, you can see if the inputs contain the password you enter from client. Script should have `return 1`  at the end to block request.

Regardless, this issue made me notice that ovpn-auth not checking if the input file contains 2 lines is leading to poor user experience. I will address this problem by making ovpn-auth return a meaningful error message on faulty logins.

**Comment by bhzhu203** [comment] 2024-05-14 07:40
> I've just tried logging in to a OpenVPN server using ovpn-auth and a password that contains letters, digits and symbols. Since it worked as faultless as before, I can say I could not reproduce your issue.
> 
> I suggest you to:
> 
>     * Check your inputs. Users are not supposed to enter their passwords until OpenVPN client explicitly prompts as `Enter Auth Password:`. If you enter your password by appending to your username that might be the problem.
> 
>     * Check your server and client configuration files. Server needs to have this line:
>       ```
>       auth-user-pass-verify /etc/openvpn/ovpn-auth via-file
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       and the client config .ovpn file should have this line:
>       ```
>       auth-user-pass
>       ```
> 
>     * Replace the ovpn-auth binary with a script that will print out (`cat $1`) the content of file which its path passed by OpenVPN. So, you can see if the inputs contain the password you enter from client. Script should have `return 1`  at the end to block request.
> 
> 
> Regardless, this issue made me notice that ovpn-auth not checking if the input file contains 2 lines is leading to poor user experience. I will address this problem by making ovpn-auth return a meaningful error message on faulty logins.

Is it about the openvpn version ?


```
cat ovpn-auth
#! /bin/bash
echo \$1=$1
/usr/bin/ovpn-auth $1
#exit 0
```


```
[root@data4 openvpn]# chattr +a /tmp
[root@data4 openvpn]# ^C
[root@data4 openvpn]# touch /tmp/d
[root@data4 openvpn]# rm -v  /tmp/d
rm: remove regular empty file '/tmp/d'? y
rm: cannot remove '/tmp/d': Operation not permitted
[root@data4 openvpn]# fg
openvpn openvpn.conf
^C2024-05-14 15:30:59 net_addr_v4_del: 192.168.136.1 dev tun5
2024-05-14 15:30:59 SIGINT[hard,] received, process exiting
[root@data4 openvpn]# openvpn openvpn.conf 
2024-05-14 15:31:11 Note: Treating option '--ncp-ciphers' as  '--data-ciphers' (renamed in OpenVPN 2.5).
2024-05-14 15:31:11 OpenVPN 2.5.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Sep 23 2021
2024-05-14 15:31:11 library versions: OpenSSL 1.1.1g FIPS  21 Apr 2020, LZO 2.08
2024-05-14 15:31:11 WARNING: --keepalive option is missing from server config
2024-05-14 15:31:11 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2024-05-14 15:31:11 TUN/TAP device tun5 opened
2024-05-14 15:31:11 net_iface_mtu_set: mtu 1500 for tun5
2024-05-14 15:31:11 net_iface_up: set tun5 up
2024-05-14 15:31:11 net_addr_v4_add: 192.168.136.1/24 dev tun5
2024-05-14 15:31:11 setsockopt(IPV6_V6ONLY=0)
2024-05-14 15:31:11 Listening for incoming TCP connection on [AF_INET6][undef]:7777
2024-05-14 15:31:11 TCPv6_SERVER link local (bound): [AF_INET6][undef]:7777
2024-05-14 15:31:11 TCPv6_SERVER link remote: [AF_UNSPEC]
2024-05-14 15:31:11 Initialization Sequence Completed
2024-05-14 15:31:16 TCP connection established with [AF_INET6]::ffff:10.10.10.139:60832
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_VER=2.4.6
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_PLAT=linux
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_PROTO=2
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_NCP=2
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_LZ4=1
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_LZ4v2=1
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_LZO=1
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_COMP_STUB=1
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_COMP_STUBv2=1
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_TCPNL=1
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_HWADDR=00:e0:70:d7:7c:ed
2024-05-14 15:31:17 10.10.10.139:60832 peer info: IV_SSL=OpenSSL_1.0.2j__26_Sep_2016
2024-05-14 15:31:17 10.10.10.139:60832 peer info: UV_ID=f8c382c7c2354c8a9a71266e9ae62b08
2024-05-14 15:31:17 10.10.10.139:60832 peer info: UV_NAME=lively-meadow-2754
$1=/tmp/openvpn_up_2438a2c32658b84466e072b002b871da.tmp
checking login: totp nonce is invalid
2024-05-14 15:31:17 10.10.10.139:60832 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 1
2024-05-14 15:31:17 10.10.10.139:60832 TLS Auth Error: Auth Username/Password verification failed for peer
2024-05-14 15:31:17 10.10.10.139:60832 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1560', remote='link-mtu 1552'
2024-05-14 15:31:17 10.10.10.139:60832 WARNING: 'auth' is used inconsistently, local='auth SHA1', remote='auth [null-digest]'
2024-05-14 15:31:17 10.10.10.139:60832 [5af3e3483f892a016098f0fd] Peer Connection Initiated with [AF_INET6]::ffff:10.10.10.139:60832
2024-05-14 15:31:18 10.10.10.139:60832 Connection reset, restarting [0]
2024-05-14 15:31:52 TCP connection established with [AF_INET6]::ffff:10.10.10.139:52484
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_VER=2.4.6
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_PLAT=linux
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_PROTO=2
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_NCP=2
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_LZ4=1
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_LZ4v2=1
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_LZO=1
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_COMP_STUB=1
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_COMP_STUBv2=1
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_TCPNL=1
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_HWADDR=00:e0:70:d7:7c:ed
2024-05-14 15:31:53 10.10.10.139:52484 peer info: IV_SSL=OpenSSL_1.0.2j__26_Sep_2016
2024-05-14 15:31:53 10.10.10.139:52484 peer info: UV_ID=f8c382c7c2354c8a9a71266e9ae62b08
2024-05-14 15:31:53 10.10.10.139:52484 peer info: UV_NAME=lively-meadow-2754
$1=/tmp/openvpn_up_55994fc70fff098e4941214776ed9b2c.tmp
2024-05-14 15:31:54 10.10.10.139:52484 [5af3e3483f892a016098f0fd] Peer Connection Initiated with [AF_INET6]::ffff:10.10.10.139:52484
2024-05-14 15:31:54 5af3e3483f892a016098f0fd/10.10.10.139:52484 MULTI_sva: pool returned IPv4=192.168.136.2, IPv6=(Not enabled)
^Z
[2]+  Stopped                 openvpn openvpn.conf
[root@data4 openvpn]# cat /tmp/openvpn_up_55994fc70fff098e4941214776ed9b2c.tmp
dhb
1646400
[root@data4 openvpn]# fg
openvpn openvpn.conf


2024-05-14 15:32:43 5af3e3483f892a016098f0fd/10.10.10.139:52484 Connection reset, restarting [0]
2024-05-14 15:33:44 TCP connection established with [AF_INET6]::ffff:10.10.10.139:51460
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_VER=2.4.6
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_PLAT=linux
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_PROTO=2
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_NCP=2
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_LZ4=1
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_LZ4v2=1
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_LZO=1
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_COMP_STUB=1
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_COMP_STUBv2=1
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_TCPNL=1
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_HWADDR=00:e0:70:d7:7c:ed
2024-05-14 15:33:45 10.10.10.139:51460 peer info: IV_SSL=OpenSSL_1.0.2j__26_Sep_2016
2024-05-14 15:33:45 10.10.10.139:51460 peer info: UV_ID=f8c382c7c2354c8a9a71266e9ae62b08
2024-05-14 15:33:45 10.10.10.139:51460 peer info: UV_NAME=lively-meadow-2754
$1=/tmp/openvpn_up_717d0d5e03bfcddc32eaec0eebdac7.tmp
checking login: password mismatch
2024-05-14 15:33:45 10.10.10.139:51460 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 1
2024-05-14 15:33:45 10.10.10.139:51460 TLS Auth Error: Auth Username/Password verification failed for peer
2024-05-14 15:33:45 10.10.10.139:51460 [5af3e3483f892a016098f0fd] Peer Connection Initiated with [AF_INET6]::ffff:10.10.10.139:51460
2024-05-14 15:33:46 10.10.10.139:51460 Connection reset, restarting [0]
^Z
[2]+  Stopped                 openvpn openvpn.conf
[root@data4 openvpn]# cat /tmp/openvpn_up_717d0d5e03bfcddc32eaec0eebdac7.tmp
zhenyi2
7758a303234
```

**Comment by ufukty** [comment] 2024-05-14 08:52
Have you checked the content of passes file? In this case the file name is `/tmp/openvpn_up_2438a2c32658b84466e072b002b871da.tmp`

Other than that I assume your system time is correct

**Comment by ufukty** [comment] 2024-05-14 09:25
I've now realized last dump contains two attempt. Both looks okay for syntax. 

```
dhb
1646400
```
This one returned with invalid TOTP error so, password validated correctly. 

```  
zhenyi2
7758a303234
```  
This one returned with password mismatch, so TOTP is never checked. 

I understand the issue doesn't occur because of wrongly formed input. 

Is the database file up to date? If you try to register with same username it should override the previous password. 

You can try to re-register with name of `zhenyi2` and password `7758a`. Just to make sure database is up to date. You might delete the database file altogether before start. 

Alternatively you can check if the hash in database file is valid for your password by using an online argon2 hash validator, [one example](https://argon2.online/).

**Comment by ufukty** [comment] 2024-05-14 11:38
I've published [v1.0.5](https://github.com/ufukty/ovpn-auth/releases/tag/v1.0.5) to add `validate` mode.

**Comment by bhzhu203** [comment] 2024-05-18 02:37
I have try the latest version ,the issue is solved 

> I've now realized last dump contains two attempt. Both looks okay for syntax.
> 
> ```
> dhb
> 1646400
> ```
> 
> This one returned with invalid TOTP error so, password validated correctly.
> 
> ```
> zhenyi2
> 7758a303234
> ```
> 
> This one returned with password mismatch, so TOTP is never checked.
> 
> I understand the issue doesn't occur because of wrongly formed input.
> 
> Is the database file up to date? If you try to register with same username it should override the previous password.
> 
> You can try to re-register with name of `zhenyi2` and password `7758a`. Just to make sure database is up to date. You might delete the database file altogether before start.
> 
> Alternatively you can check if the hash in database file is valid for your password by using an online argon2 hash validator.
> 
> **Update**: Don't bother with the link I post before. I've decided to implement an interactive login command `validate` to simulate login flow, to catch login errors easier, without requiring OpenVPN intervention.

**Comment by ufukty** [comment] 2024-05-18 04:23
Nice to hear. I'm gonna close the issue now.

**Closed by ufukty** 2024-05-18 04:23 UTC
